language: node_js
node_js:
  - 6.9.1
  notifications:
    email:
    on_failure: change
    on_success: change

  addons:
    ssh_known_hosts:
      -45.55.247.148
  branches:
    only:
      -master
    env:
      global:
        - REMOTE_APP_DIR=/var/www/cuisinely/
        - REMOTE_USER=deploy
        - REMOTE_HOST=45.55.247.148
        - PORT=8080
        before_install:
          -npm install -g npm@^2
        install:
        - npm install --only=dev
       after_success:
        - chmod 600 deploy && mv deploy ~/.ssh/id_rsa

